<?php
function arctic_theme(){
 return array(
   'arctic_menu' => array(
     'template' => 'tpl/arctic_menu',
   ),
   'arctic_menu_icon' => array(
     'template' => 'tpl/arctic_menu_icon',
   ),
   'arctic_reports' => array(
     'template' => 'tpl/arctic_reports',
   ),
   'arctic_reports_rank' => array(
     'template' => 'tpl/arctic_reports_rank',
   ),
   'arctic_reports_traffic' => array(
     'template' => 'tpl/arctic_reports_traffic',
   ),
   'arctic_reports_leads' => array(
     'template' => 'tpl/arctic_reports_leads',
   ),
   'arctic_seo' => array(
     'template' => 'tpl/arctic_seo',
   ),
   'arctic_campaign' => array(
     'template' => 'tpl/campaign/dashboard',
   ),
   'arctic_campaign_info' => array(
     'template' => 'tpl/campaign/info',
   ),
   'arctic_campaign_launch' => array(
     'template' => 'tpl/campaign/launch',
   ),
   'arctic_campaign_citations' => array(
     'template' => 'tpl/campaign/citations',
   ),
   'arctic_campaign_onpage' => array(
     'template' => 'tpl/campaign/onpage',
   ),
   'arctic_campaign_maintenance' => array(
     'template' => 'tpl/campaign/maintenance',
   ),
   'arctic_deliverables' => array(
     'template' => 'tpl/arctic_deliverables',
   ),
   'arctic_support' => array(
     'template' => 'tpl/arctic_support',
   ),
   'arctic_convert_builder' => array(
     'template' => 'tpl/arctic_convert_builder',
   ),
   'arctic_convert_bar' => array(
     'template' => 'tpl/arctic_convert_bar',
   ),
   'arctic_convert_mat' => array(
     'template' => 'tpl/arctic_convert_mat',
   ),
   'arctic_convert_takeover' => array(
     'template' => 'tpl/arctic_convert_takeover',
   ),
   'arctic_convert_slider' => array(
     'template' => 'tpl/arctic_convert_slider',
   ),
   'arctic_convert_dialog' => array(
     'template' => 'tpl/arctic_convert_dialog',
   ),
   'arctic_convert_sidebar' => array(
     'template' => 'tpl/arctic_convert_sidebar',
   ),
 );
}
