<?php
function arctic_help($section = 'admin/help#arctic', $arg = null){
  $output = '';

  switch ($section) {
    case 'admin/help#arctic':
      $output .= '';
      break;
    case 'admin/arctic':
      $output .= '';
      break;
    case 'admin/arctic/reports/rank':
      $output .= '';
      break;
    case 'admin/arctic/reports/traffic':
      $output .= '';
      break;
    case 'admin/arctic/reports/leads':
      $output .= '';
      break;
    case 'admin/arctic/support':
      $output .= '';
      break;
    case 'admin/arctic/settings':
      $output .= '';
      break;
  }

  return $output;
}
